//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuvantuyensinhsv.v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SachChoMuon
    {
        public int id_sach { get; set; }
        public string id_nguoidung { get; set; }
        public Nullable<bool> loai { get; set; }
        public string diachi { get; set; }
        public string comment { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
