//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tuvantuyensinhsv.v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruongNganhMonthi
    {
        public string MaTruong { get; set; }
        public string MaNganh { get; set; }
        public int idMon1 { get; set; }
        public int idMon2 { get; set; }
        public int idMon3 { get; set; }
        public int Nam { get; set; }
        public double Diem { get; set; }
        public int SoLuongTruyCap { get; set; }
    
        public virtual Nganh Nganh { get; set; }
        public virtual Truong Truong { get; set; }
    }
}
